theme: jekyll-theme-merlot
title: Welcome to Nutrients Calculator!
dscription: By using this tool you could calculate your daily nutrients intake and compare to recommended guidelines, which couly promote a healthy lifestyle!
